database {
    driver = "org.postgresql.Driver"
    jdbcUrl = ${?DB_URL}
    user = ${?DB_USER}
    password = ${?DB_PASSWORD}
    maxPoolSize = 20
}

app {
    cors {
        anyHost = false
    }

    rateLimit {
        requestsPerMinute = 500
    }
}